### ISSUE TITLE
Unable to install plugins when setting up PowerShell Jenkins for the first time

### ISSUE THREAD

**Issue by meghasinghal1** [matt9ucci/docker-jenkins-powershell#1]
I am unable to install plugins when setting up PowerShell Jenkins for the first time., Could someone please suggest what I am missing here?

![image](https://user-images.githubusercontent.com/13881466/215242156-0152b482-938f-42f2-9ea6-ca047b92ad6b.png)

**Comment by matt9ucci** [comment]
@meghasinghal1 The screenshot shows your Jenkins version is old 2.249.2. I have just pushed the latest image, version 2.375.2, to [Docker Hub](https://hub.docker.com/repository/docker/matt9ucci/jenkins-powershell/tags). Give it a try!

**Comment by meghasinghal1** [comment]
Sure let me try

**Comment by meghasinghal1** [comment]
First of all, thank you so much for your response on my query. I really appreciate this.

I have actually tried to install the plugin with latest version and able to install successfully. Could you please suggest what am I expected to do to run my PowerShell code as I am still getting this error

**Cannot run program "powershell"**  

Thanks in advance :)

**Comment by meghasinghal1** [comment]
Adding some screenshots for your references

This is how I am getting an error on console - 
![image](https://user-images.githubusercontent.com/13881466/215281892-b4050a15-8c33-46fb-abb9-4520d89e3df0.png)

And this is how I kept PowerShell code in my Jenkins script - 
![image](https://user-images.githubusercontent.com/13881466/215282026-055d60a2-70ab-48c4-b2eb-efd2e5949c08.png)

**Comment by matt9ucci** [comment]
Try to replace `powershell` with `pwsh` in your script.

Here is my working pipeline script:
```
node {
    pwsh '''
        Write-Host "Hello, docker-jenkins-powershell!"
    '''
}
```

The "Console Output" of Jenkins is:
```
Started by user XXXX
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /var/jenkins_home/workspace/pstest
[Pipeline] {
[Pipeline] pwsh
Hello, docker-jenkins-powershell!
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

Since v6.0, PowerShell started supporting Linux and Mac, and renamed `powershell` with `pwsh`. `powershell` can be used for older PowerShell versions on Windows. On Linux (this docker image), PowerShell is `pwsh`. 
For more information, see the official Jenkins doc "[Pipeline: Nodes and Processes](https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/)".

**Comment by meghasinghal1** [comment]
thanks for your response. ok let me check on it

**Comment by meghasinghal1** [comment]
Yes it is working as expected. thanks you so much.

You have created a very useful tool and thank you so much for that.
